ExecInterface:

	java classes.interfaceGrafica.InterfacePrincipal

compAll:

	javac -d . funcional/Atributos/*.java
	javac -d . funcional/Tools/*.java
	javac -d . interface/*.java

compInterface:

	javac -d . interface/*.java

compTools:

	javac -d . funcional/Tools/*.java

compAtributos:

	javac -d . funcional/Atributos/*.java


